### ISSUE TITLE
Cleanup description on homepage

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#70]
It's very long. maybe move it to new page or add a tooltip under the link to "better alternative"?
![image](https://github.com/MeetAsOne/MeetAsOne/assets/22477298/cad24b65-2d44-4e90-939e-2881f2c6ddc7)

**Comment by funblaster22** [comment]
Can you think of any other features that set apart meetasone? I'm also considering removing the time zone translation because I'm pretty sure every tool has it, but indecisive because it's a pretty important feature nonetheless. No sign in required also got cut for the reason that everyone had it. The asterisks will have tooltips on the official site.

FEATURE | MEETASONE | WHEN2MEET | LETTUCEMEET | DOODLE | RALLLY
-- | -- | -- | -- | -- | --
Import from screenshot | ✅ | ❌ | ❌ | ❌ | ❌
Save & load availability across multiple polls | ✅ | ❌ | ❌ | ❌ | ❌
Mobile-friendly | ✅ | ❌ | * (can't multiselect availability on mobile) | ❔ | ❔
Timezone translation | ✅ | ✅ | * (no choice, local tz) | ❔ | ❔
Open Source | ✅| ❌ | * (there's an open source clone) | ❌ | ✅

**Comment by funblaster22** [comment]
I already thought of one: time block interval (15 min for us), 30 for lettuce & when2meet, predetermined blocks for the other 2

**Comment by funblaster22** [comment]
Alternatively, if you can think of any alternate competitors. I might remove rally because they don't appear on the first page of Google, I just found them in a list. I could add https://whenisgood.net/ but the UI on that one is a little interesting

**Comment by funblaster22** [comment]
NEW COMPETITOR JUST DROPPED! [schej.it](https://schej.it/) and yikes, they actually look kinda good

**Comment by lectrician1** [comment]
The heading on top needs to have equal margins from the top of the page and the horizontal line. The top needs to be larger in height.

**Comment by lectrician1** [comment]
Finally, the scrolling text should have a fade-in and fade out at the bottom and top. It should also move a tiny bit slower. There should also not be a bounce-back. It's dizzying.

**Comment by lectrician1** [comment]
Finally, just put and X for lettucemeet. it's not open source. We also don't need a Github label for where meetasone is open soure. just have the checkbox. it's cluttered.
